apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flask-chart.fullname" . }}-sm
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "flask-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "flask-chart.name" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http-metrics # must match your Service port name
      interval: 30s

